### ISSUE TITLE
Error while notifying listeners and request type is not a type of POST

### ISSUE THREAD

**Issue by BuddhiWathsala** [siddhi-io/siddhi-io-http#164]
**Description:**
For the following Siddhi app deployment in K8s, I got the following error and the Siddhi runner did not come to the healthy state due to this error.

#### Siddhi App
```sql
@App:name("0.InputRoute-passthrough")

@source(type='http', receiver.url='http://0.0.0.0:9090/route', @map(type='json'))
define stream passthroughInputRouteStream(routeNo string);

@sink(type='nats',cluster.id='siddhi-stan',destination = '0.InputRoute_InputRouteStream', bootstrap.servers='nats://siddhi-nats:4222',@map(type='text'))
define stream InputRouteStream(routeNo string);

from passthroughInputRouteStream select * insert into InputRouteStream;
```

#### Error Log

```sh
[2020-01-18 02:50:47,196] ERROR {org.wso2.transport.http.netty.contractimpl.listener.states.ReceivingHeaders} - Error while notifying listeners io.siddhi.extension.io.http.source.exception.HttpSourceAdaptorRuntimeException: Request type is not a type of POST
        at io.siddhi.extension.io.http.source.HTTPConnectorListener.onMessage(HTTPConnectorListener.java:76)
        at org.wso2.transport.http.netty.contractimpl.HttpWsServerConnectorFuture.notifyHttpListener(HttpWsServerConnectorFuture.java:72)
        at org.wso2.transport.http.netty.contractimpl.listener.states.ReceivingHeaders.notifyRequestListener(ReceivingHeaders.java:98)
        at org.wso2.transport.http.netty.contractimpl.listener.states.ReceivingHeaders.readInboundRequestHeaders(ReceivingHeaders.java:77)
        at org.wso2.transport.http.netty.contractimpl.listener.states.ListenerReqRespStateManager.readInboundRequestHeaders(ListenerReqRespStateManager.java:38)
        at org.wso2.transport.http.netty.contractimpl.listener.SourceHandler.channelRead(SourceHandler.java:130)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at org.wso2.transport.http.netty.contractimpl.listener.WebSocketServerHandshakeHandler.channelRead(WebSocketServerHandshakeHandler.java:135)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at org.wso2.transport.http.netty.contractimpl.listener.UriAndHeaderLengthValidator.channelRead(UriAndHeaderLengthValidator.java:64)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Unknown Source)
```

**Affected Product Version:**
Siddhi runner 5.1.2

**Comment by pcnfernando** [comment]
Ideally this exception is thrown when a request other than a POST is received at a Siddhi Http Source. For example if you call a GET request on the source URL, this exception will be thrown. Refer the http source documentation in https://siddhi-io.github.io/siddhi-io-http/api/2.2.0/#http-source

**Comment by BuddhiWathsala** [comment]
This issue was occurred due to the fact when I started an HTTP source in `9090` port which was used by Siddhi runner and tooling to expose internal APIs such as health checks.
