### ISSUE TITLE
HTTP Source is removed when there multiple apps with same source hostname,port and context

### ISSUE THREAD

**Issue by NisalaNiroshana** [siddhi-io/siddhi-io-http#60]
**Description:**
Let's assume a scenario where we have siddhi app with HTTP source and we try to deploy another siddhi app with same HTTP source. In that case, it will remove the HTTP source from the first app also. 

**Suggested Labels:**
@Bug

**Steps to reproduce:**

- Create two siddhi apps with same HTTP source.
- Then add these siddhi apps one by one.
- It will give an error and does not allow to deploy the second app. It will also remove the HTTP source from the first app. So we cannot publish any events to that HTTP source.

**Comment by mohanvive** [comment]
It works as expected in the latest HTTP IO source implementation. It gives an error as shown below when deploying a second HTTP IO source.

```
osgi> [2019-09-25 17:26:52,387] ERROR {io.siddhi.core.stream.input.source.Source} - Error on 'SiddhiApp1'. Listener URL http://0.0.0.0:8006/ctab already connected Error while connecting at Source 'http' at 'CtabUrl'. io.siddhi.core.exception.SiddhiAppCreationException: Error on 'SiddhiApp1'. Listener URL http://0.0.0.0:8006/ctab already connected
	at io.siddhi.extension.io.http.source.HttpConnectorRegistry.registerSourceListener(HttpConnectorRegistry.java:137)
	at io.siddhi.extension.io.http.source.HttpSource.connect(HttpSource.java:419)
	at io.siddhi.core.stream.input.source.Source.connectWithRetry(Source.java:160)
	at io.siddhi.core.SiddhiAppRuntimeImpl.startSources(SiddhiAppRuntimeImpl.java:484)
	at io.siddhi.core.SiddhiAppRuntimeImpl.start(SiddhiAppRuntimeImpl.java:415)
	at io.siddhi.distribution.core.internal.StreamProcessorService.deploySiddhiApp(StreamProcessorService.java:106)
	at io.siddhi.distribution.core.internal.StreamProcessorDeployer.deploySiddhiQLFile(StreamProcessorDeployer.java:81)
	at io.siddhi.distribution.core.internal.StreamProcessorDeployer.deploy(StreamProcessorDeployer.java:175)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.lambda$deployArtifacts$0(DeploymentEngine.java:291)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.wso2.carbon.deployment.engine.internal.DeploymentEngine.deployArtifacts(DeploymentEngine.java:282)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.sweep(RepositoryScanner.java:112)
	at org.wso2.carbon.deployment.engine.internal.RepositoryScanner.scan(RepositoryScanner.java:68)
	at org.wso2.carbon.deployment.engine.internal.SchedulerTask.run(SchedulerTask.java:43)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[2019-09-25 17:26:52,389] ERROR {io.siddhi.core.SiddhiAppRuntimeImpl} - Error starting Siddhi App 'SiddhiApp1', triggering shutdown process. Error on 'SiddhiApp1'. Listener URL http://0.0.0.0:8006/ctab already connected
[2019-09-25 17:26:52,390]  INFO {io.siddhi.distribution.core.internal.StreamProcessorService} - Siddhi App SiddhiApp1 deployed successfully
```
